/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      compress.c
 * @copyright   eosgarden 2011 - Jean-David Gadina <macmade@eosgarden.com>
 * @abstract    ...
 */

#include "lzwm.h"

/*!
 * 
 */
void lzwm_compress( FILE * source, FILE * destination )
{
    bool                dict_end;
    unsigned char       c;
    char                unit[ 4 ];
    unsigned char       data[ LZWM_DATA_MAX_LENGTH ];
    unsigned int        i;
    unsigned int        j;
    unsigned int        k;
    unsigned int        n;
    unsigned int        p;
    unsigned int        length;
    unsigned long       read_ops;
    unsigned long       read_op;
    unsigned char       read_buffer[ LZWM_READ_BUFFER_LENGTH ];
    uint16_t            write_buffer[ LZWM_WRITE_BUFFER_LENGTH ];
    double              hsize;
    size_t              size;
    size_t              bytes;
    lzwm_dict         * dict;
    lzwm_code         * code;
    lzwm_code         * prev_code;
    libprogressbar_args args;
    
    DEBUG( "Initializing the LZW dictionnary" );
    
    if( NULL == ( dict = lzwm_create_dict() ) )
    {
        printf( "Error: cannot initialize the LZW dictionnary.\n" );
        return;
    }
    
    n        = 1;
    size     = fsize( source );
    hsize    = fhsize( source, unit );
    read_ops = ceil( ( double )size / ( double )LZWM_READ_BUFFER_LENGTH );
    read_op  = 0;
    i        = 0;
    j        = 0;
    k        = 0;
    p        = 0;
    bytes    = 0;
    dict_end = false;
    code     = NULL;
    
    if( libdebug_is_enabled() == false )
    {
        args.percent = &p;
        args.length  = 50;
        args.label   = "Compressing file:";
        args.done    = "[OK]";
        
        libprogressbar_create_progressbar( ( void * )( &args ) );
    }
    
    DEBUG( "Writing file ID (%s)", LZWM_FILE_ID );
    fwrite( LZWM_FILE_ID, sizeof( uint8_t ), strlen( LZWM_FILE_ID ), destination );
    
    memset( data, 0, LZWM_DATA_MAX_LENGTH );
    memset( write_buffer, 0, LZWM_WRITE_BUFFER_LENGTH );
    fread( data, sizeof( unsigned char ), 1, source );
    DEBUG( "First character: 0x%02X - %03u (%c)", data[ 0 ], data[ 0 ], ( isprint( data[ 0 ] ) ) ? data[ 0 ] : '.' );
    
    prev_code = &( dict->codes[ data[ 0 ] ] );
    
    while( ( length = fread( read_buffer, sizeof( unsigned char ), LZWM_READ_BUFFER_LENGTH, source ) ) )
    {
        DEBUG( "Reading data from source file" );
        
        read_op++;
        
        for( i = 0; i < length; i++ )
        {
            c         = read_buffer[ i ];
            data[ n ] = c;
            
            if( dict->count == LZWM_DICT_ALLOC )
            {
                DEBUG( "Maximum number of codes reached. Creating a new LZW dictionary.\n" );
                
                lzwm_delete_dict( dict );
                
                if( NULL == ( dict = lzwm_create_dict() ) )
                {
                    printf( "Error: cannot initialize the LZW dictionnary.\n" );
                    return;
                }
                
                if( j == LZWM_WRITE_BUFFER_LENGTH )
                {
                    lzwm_compress_write( dict, write_buffer, LZWM_WRITE_BUFFER_LENGTH, bytes, destination );
                    
                    j     = 0;
                    bytes = 0;
                }
                
                DEBUG( "Writing dictionary end marker" );
                
                write_buffer[ j++ ] = LZWM_DICT_MARKER_END;
                prev_code           = &( dict->codes[ c ] );
                
                memset( data, 0, LZWM_DATA_MAX_LENGTH );
                
                data[ 0 ] = c;
            }
            
            if( NULL == ( code = lzwm_find_dict_entry( dict, data, n + 1 ) ) )
            {
                if( j == LZWM_WRITE_BUFFER_LENGTH )
                {
                    lzwm_compress_write( dict, write_buffer, LZWM_WRITE_BUFFER_LENGTH, bytes, destination );
                    
                    j     = 0;
                    bytes = 0;
                }
                
                DEBUG( "    - Writing data to the buffer:         0x%03X - %03u (%s)", prev_code->code, prev_code->code, prev_code->data );
                
                write_buffer[ j++ ] = prev_code->code;
                bytes              += prev_code->length;
                
                DEBUG( "    - Symbol not found: adding new entry: 0x%03X - %03u (%s)", dict->count, dict->count, data );
                lzwm_add_dict_entry( dict, data, n + 1 );
                memset( data, 0, LZWM_DATA_MAX_LENGTH );
                
                data[ 0 ] = c;
                n         = 1;
                prev_code = &( dict->codes[ c ] );
            }
            else
            {
                DEBUG( "    - Symbol found:                       0x%03X - %03u (%s)", code->code, code->code, code->data );
                prev_code = code;
                
                n++;
            }
        }
        
        p = ( ( double )read_op / ( double )read_ops ) * 100;
    }
    
    if( j > 0 || prev_code )
    {
        write_buffer[ j++ ] = prev_code->code;
        bytes              += prev_code->length;
        
        lzwm_compress_write( dict, write_buffer, j, bytes, destination );
    }
    
    p = 100;
    
    libprogressbar_end();
    
    lzwm_delete_dict( dict );
}
  
/*!
 * 
 */
void lzwm_compress_write( lzwm_dict * dict, uint16_t * buffer, size_t length, size_t bytes, FILE * destination )
{
    unsigned int i;
    unsigned int j;
    unsigned int n;
    uint8_t    * char_buffer;
    lzwm_code  * code;
    uint16_t     shrt;
    uint16_t     marker_8bits;
    uint16_t     marker_16bits;
    
    marker_8bits  = LZWM_DICT_MARKER_8BITS;
    marker_16bits = LZWM_DICT_MARKER_16BITS;
    i             = 0;
    j             = 0;
    n             = 0;
    
    DEBUG( "Writing data to the destination file" );
    DEBUG( "Checking compression ratio" );
    
    if( bytes > ( length * sizeof( uint16_t ) ) )
    {
        DEBUG( "Saved %lu bytes: writing 16 bits codes.", bytes - ( length * sizeof( uint16_t ) ) );
        fwrite( &marker_16bits, sizeof( uint16_t ), 1, destination );
        fwrite( buffer, sizeof( uint16_t ), length, destination );
    }
    else
    {
        DEBUG( "No byte saved: writing 8 bits data" );
        
        if( NULL == ( char_buffer = ( ( uint8_t * )malloc( sizeof( uint8_t ) * bytes ) ) ) )
        {
            ERROR( "Out of memory" );
        }
        
        for( i = 0; i < length; i++ )
        {
            shrt = buffer[ i ];
            
            if( shrt == LZWM_DICT_MARKER_END )
            {
                char_buffer[ n++ ] = ( uint8_t )( LZWM_DICT_MARKER_END >> 8 );
                char_buffer[ n++ ] = ( uint8_t )( LZWM_DICT_MARKER_END & 0xFF00 );
                continue;
            }
            
            code = &( dict->codes[ shrt ] );
            
            for( j = 0; j < code->length; j++ )
            {
                char_buffer[ n++ ] = code->data[ j ];
            }
        }
        
        fwrite( &marker_8bits, sizeof( uint16_t ), 1, destination );
        fwrite( &bytes, sizeof( size_t ), 1, destination );
        fwrite( char_buffer, sizeof( uint8_t ), bytes, destination );
        free( char_buffer );
    }
}
